# Generated by Django 5.0.3 on 2024-04-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basicapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_Num", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="lobo",
            name="claim_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="lobo",
            name="time_seen",
            field=models.DateTimeField(),
        ),
    ]
