# Generated by Django 5.0.3 on 2024-04-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basicapp", "0003_user_email_alter_user_phone_num"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AlterField(
            model_name="lobo",
            name="is_claimed",
            field=models.BooleanField(default=False),
        ),
    ]
